### ISSUE TITLE
Dockerize Postgres

### ISSUE THREAD

**Issue by imcodingideas** [modernproject/local#2]
If I work on a PR to dockerize postgres, would you merge it?

**Comment by djstein** [comment]
@imcodingideas what ideas do you have to make to the addition of the current image?

**Comment by djstein** [comment]
some thoughts on why it is the way it currently is:
- no version is specified. this will result in the latest version being pulled. this is such that when I work on this it ensures that the other dependencies work with the most MODERN version
- there is one line of copying to the docker entrypoint, which for some users has to be used and is more of a mental note here
- the image gets named to modernproject/postgres on `docker-compose up|build` only for the virtual network
- the image is not used in the prod repository and thus was no needed to be built out. in production an RDS database is used instead.

**Comment by imcodingideas** [comment]
Hello,

Sure, what I wanted to do was add default environment variables to the docker file. 

```
   environment:
      ENV: ''
      POSTGRES_NAME: ''
      POSTGRES_USER: ''
      POSTGRES_PASSWORD: ''
      POSTGRES_HOST: ''
    depends_on:
      - web

```

So we don't need to configure `POSTGRES_*` in the .env. Clearly, I think we would need a script to create the database `docker-compose run backend db:create` but that is what I was thinking.

Thoughts?
